/**
 * This class file was automatically generated by jASN1 v1.5.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerBitString;

public class ACSE_requirements extends BerBitString {

	public ACSE_requirements() {
	}

	public ACSE_requirements(byte[] code) {
		super(code);
	}

	public ACSE_requirements(byte[] value, int numBits) {
		super(value, numBits);
	}

}
