/**
 * This class file was automatically generated by jASN1 v1.5.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerOctetString;

public class AE_qualifier_form2 extends BerOctetString {

	public AE_qualifier_form2() {
	}

	public AE_qualifier_form2(byte[] value) {
		super(value);
	}

}
