/**
 * This class file was automatically generated by jASN1 v1.5.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerObjectIdentifier;

public class AE_title_form2 extends BerObjectIdentifier {

	public AE_title_form2() {
	}

	public AE_title_form2(byte[] code) {
		super(code);
	}

	public AE_title_form2(int[] value) {
		super(value);
	}

}
