/**
 * This class file was automatically generated by jASN1 v1.5.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerInteger;

public class AP_invocation_identifier extends BerInteger {

	public AP_invocation_identifier() {
	}

	public AP_invocation_identifier(byte[] code) {
		super(code);
	}

	public AP_invocation_identifier(long value) {
		super(value);
	}

}
