/**
 * This class file was automatically generated by jASN1 v1.5.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerOctetString;

public class AP_title_form2 extends BerOctetString {

	public AP_title_form2() {
	}

	public AP_title_form2(byte[] value) {
		super(value);
	}

}
