/**
 * This class file was automatically generated by jASN1 v1.5.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerObjectIdentifier;

public class Application_context_name extends BerObjectIdentifier {

	public Application_context_name() {
	}

	public Application_context_name(byte[] code) {
		super(code);
	}

	public Application_context_name(int[] value) {
		super(value);
	}

}
