/**
 * This class file was automatically generated by jASN1 v1.5.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.BerByteArrayOutputStream;
import org.openmuc.jasn1.ber.BerIdentifier;
import org.openmuc.jasn1.ber.types.BerBitString;
import org.openmuc.jasn1.ber.types.BerOctetString;

public class Authentication_value {

	public byte[] code = null;
	public BerOctetString charstring = null;

	public BerBitString bitstring = null;

	public Authentication_value() {
	}

	public Authentication_value(byte[] code) {
		this.code = code;
	}

	public Authentication_value(BerOctetString charstring, BerBitString bitstring) {
		this.charstring = charstring;
		this.bitstring = bitstring;
	}

	public int encode(BerByteArrayOutputStream os, boolean explicit) throws IOException {
		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			return code.length;

		}
		int codeLength = 0;
		if (bitstring != null) {
			codeLength += bitstring.encode(os, false);
			// write tag {CONTEXT_CLASS, PRIMITIVE, 1}
			os.write(0x81);
			codeLength += 1;
			return codeLength;

		}

		if (charstring != null) {
			codeLength += charstring.encode(os, false);
			// write tag {CONTEXT_CLASS, PRIMITIVE, 0}
			os.write(0x80);
			codeLength += 1;
			return codeLength;

		}

		throw new IOException("Error encoding BerChoice: No item in choice was selected.");
	}

	public int decode(InputStream is, BerIdentifier berIdentifier) throws IOException {
		int codeLength = 0;
		BerIdentifier passedIdentifier = berIdentifier;

		if (berIdentifier == null) {
			berIdentifier = new BerIdentifier();
			codeLength += berIdentifier.decode(is);
		}
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 0)) {
			charstring = new BerOctetString();
			codeLength += charstring.decode(is, false);
			return codeLength;
		}

		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 1)) {
			bitstring = new BerBitString();
			codeLength += bitstring.decode(is, false);
			return codeLength;
		}

		if (passedIdentifier != null) {
			return 0;
		}
		throw new IOException("Error decoding BerChoice: Identifier matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		BerByteArrayOutputStream os = new BerByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	@Override
	public String toString() {
		if (charstring != null) {
			return "CHOICE{charstring: " + charstring + "}";
		}

		if (bitstring != null) {
			return "CHOICE{bitstring: " + bitstring + "}";
		}

		return "unknown";
	}

}
