/**
 * This class file was automatically generated by jASN1 v1.5.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.string.BerGraphicString;

public class Implementation_data extends BerGraphicString {

	public Implementation_data() {
	}

	public Implementation_data(byte[] value) {
		super(value);
	}

}
