/**
 * This class file was automatically generated by jASN1 v1.5.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerInteger;

public class Release_request_reason extends BerInteger {

	public Release_request_reason() {
	}

	public Release_request_reason(byte[] code) {
		super(code);
	}

	public Release_request_reason(long value) {
		super(value);
	}

}
